### ISSUE TITLE
获取app_token报错

### ISSUE THREAD

**Issue by chenqs000** [huangshihai/mimotion#33]
获取app_token返回【"error_code": "0125"】

**Comment by YaoWe-Yang** [comment]
同样问题，也没有查到0125是啥错🤔
获取app_token
{'error_code': '0125'}
Traceback (most recent call last):
  File "main.py", line 242, in <module>
    getBeijinTime()
  File "main.py", line 98, in getBeijinTime
    msg_mi += main(user_mi, passwd_mi, min_1, max_1)
  File "main.py", line 195, in main
    app_token = get_app_token(login_token)
  File "main.py", line 235, in get_app_token
    app_token = response['token_info']['app_token']
KeyError: 'token_info'
Error: Process completed with exit code 1.

**Comment by l666l** [comment]
> 同样问题，也没有查到0125是啥错🤔 获取app_token {'error_code': '0125'} Traceback (most recent call last): File "main.py", line 242, in getBeijinTime() File "main.py", line 98, in getBeijinTime msg_mi += main(user_mi, passwd_mi, min_1, max_1) File "main.py", line 195, in main app_token = get_app_token(login_token) File "main.py", line 235, in get_app_token app_token = response['token_info']['app_token'] KeyError: 'token_info' Error: Process completed with exit code 1.

听说接口挂了，不知真假
